### ISSUE TITLE
Tab and Page context menu support

### ISSUE THREAD

**Issue by yfdyh000** [M-Reimer/undoclosetab#10]
A user requests it in my fork add-on page (out of date), I now think it's a good idea for user interface.
FYI: https://github.com/yfdyh000/undoclosetab/commit/d073acaa331aaaf319ac972a6540af1fad228b79

Thinking:
Provide options to hide these menus? Some users are tired of clutter. code FYI: https://github.com/yfdyh000/undoclosetab/commit/2f133756dcc36016afc31ef104468b3d8a6fe432 & https://github.com/yfdyh000/undoclosetab/commit/69f68dd30887689293557b76c14179c7a5b23f71.
Do max menu items limit? History for many windows may will beyond the screen size and get a scroll menu.

**Comment by M-Reimer** [comment]
Max menu items limit is finished. I'll have a look at the additional menus (page and tab) later.

**Comment by M-Reimer** [comment]
Finished now. Can you create a pull request with the missing zh_CN translations?
