### ISSUE TITLE
Please Add Hotkey Support

### ISSUE THREAD

**Issue by markran** [M-Reimer/undoclosetab#104]
I'm supporting a person with physical limitations and need a hotkey that simply performs the same action as clicking the app's icon. A hotkey will allow us to script needed functionality for her.

Thanks!

**Comment by M-Reimer** [comment]
Exists even without my Add-on. Firefox itself binds "Ctrl + Shift + T" for this.

**Comment by markran** [comment]
Ah, we didn't know that! Thank you!

**Comment by M-Reimer** [comment]
Exists even without my Add-on. Firefox itself binds "Ctrl + Shift + T" for this.

**Comment by M-Reimer** [comment]
Thanks for your feedback
