### ISSUE TITLE
Not working for me in Firefox 96.0.1

### ISSUE THREAD

**Issue by DrDaveD** [M-Reimer/undoclosetab#105]
I recently upgraded to Firefox 96.0.1 (on MacOS 10.15.7) and now when I left click on the unclosetab icon nothing happens and when I right click I get the following menu:
```
Manage Extension
Remove Extension
Report Extension
---
Pin to Overflow Menu
Remove from Toolbar
---
Bookmarks Toolbar ->
---
Customize Toolbar...
```
Basically, it's the default right-click menu I see on all the extension icons I have except for NoScript.

Is anybody else having a similar or different experience on this Firefox version?

The undoclosetab version I have is 7.4.0.

**Comment by M-Reimer** [comment]
Can you please try resetting your browser session? The first link on this projects README tells you how.

**Comment by rzetzsche** [comment]
@M-Reimer Hi there is no checkbox which is called "Restore previous session". It's called "Open previous windows and tabs" and its deactivated for me. I've tried to activate and deactivate again, but did not help.

**Comment by rzetzsche** [comment]
@M-Reimer ok after I toggled "browser.sessionstore.restore_on_demand" in about:config it now works again.

**Comment by DrDaveD** [comment]
I had already done a restart with "Open previous windows and tabs" deactivated.  I also just now tried it with browser.sessionstore.restore_on_demand" in about:config set to false.  It's still broken.  However I also still had the option to "Restore previous session" so I don't know if there's some other about:config option I also need to change.

**Comment by M-Reimer** [comment]
OK. That's a potentially interesting case. So you can actually close the browser with a session that only contains, for example, a few Wikipedia pages, restart and still have my Add-on non-working?

If that's the case: Would you be willing to share the sessionstore file of your "bugged" profile with me so I can try if I'm able to get a test case going? I'm not sure if this is possible at all by just putting this file into a new, empty, profile but if it is, I could probably finally find out what is actually going on here.

**Comment by DrDaveD** [comment]
I sent the sessionstore info by direct email.

**Comment by M-Reimer** [comment]
So far nothing arrived in my inbox

**Comment by M-Reimer** [comment]
In case gmx.de returns the mail to you because of "too large", please tell me how big the file actually is. I have a second mail address which maybe allows bigger mails.

**Comment by DrDaveD** [comment]
I had sent you a message with a [google drive link](manuel.reimer@gmx.de) so it's strange that it didn't get through.  Now I shared it directly with your gmx.de email address from google drive; if that's not the one you want to use go ahead and request another email address.

My message said
> I have several files and directories that include the word "session" under ~/Library/Application Support/Firefox/Profiles/kdso08sl.default, just not one that is obviously "sessionstore," so I put all the files including "session" in a tarball.  Please let me know when you have downloaded it so I can delete it.  I also have three pinned tabs.  I don't know if they might have something to do with it or not.  Let me know if there's any other way I can help you figure this out.

**Comment by M-Reimer** [comment]
I am able to see your folder but Google tells me that it's empty...

**Comment by DrDaveD** [comment]
That's annoying.  It's not a folder at all, it's a file called session.tgz.  Looking at it in Firefox shows me the contents of the tarball and it also gives me a download link.  Do you get the same results with [this link](https://drive.google.com/file/d/14ZGBetRud5rU2Qf-H-VL42Meil4SqDqW/view)?

**Comment by M-Reimer** [comment]
This actually worked. Thanks for sharing. I've downloaded the file to my laptop and will try to reproduce the issue as soon as I find the time to do it.

Best case this would finally allow me to actually see this issue for the first time. I have several machines, all with "Restore session" activated, in hope I ever run into this, but no luck so far.

I did Firefox development in the past so if I find out what is wrong here, I would try to fix this directly in Firefox and get a fix committed by Mozilla. As a second measure I would try to get this case detected in my Add-on to display a page with instructions on how to fix the problem.

To fix your profile, you can try to delete the file "sessionstore.jsonlz4" which seems to be the file that was most recently changed in this archive. If it is missing completely, maybe Firefox restores something from the "sessionstore-backup" folder, so rename it so Firefox does not see this folder.

**Comment by DrDaveD** [comment]
I quit Firefox, renamed sessionstore-backup and sessionstore.jsonlz4, and restarted Firefox.   It no longer had my pinned tabs nor gave me the option of restoring the previous session, but unfortunately I still had the same behavior from undoclosetab.  So that doesn't bode well that the info I sent you will allow you to reproduce the problem.  I did a force quit on Firefox, removed the new sessionstore-backup directory (there was no sessionstore.jsonlz4) and restored the two old files and then my history and pinned tabs came back (but not undoclosetab, as expected).

**Comment by DrDaveD** [comment]
I upgraded to Firefox 96.0.2 and now it is working again.

**Comment by DrDaveD** [comment]
The problem has reappeared in Firefox 97.0.1.  I went through all the same steps as before, nothing has made it work.  The directory name is "sessionstore-backups" with an ending "s"; I don't know if that was a typo above or if the name changed.  There's also a "sessionCheckpoints.json" that is updated each time, I don't know if that's new either.  Renaming that doesn't help either, it just gets recreated.

**Comment by DrDaveD** [comment]
Now it is inexplicably working again.  I didn't do anything, didn't even exit Firefox.  So I don't know what happened, but anyway it's not a problem now.
