### ISSUE TITLE
Submenu in tab bar context menu

### ISSUE THREAD

**Issue by nollinvoyd** [M-Reimer/undoclosetab#108]
Submenu in tab bar context menu does not appear.

Submenu in page  context menu works.

Firefox 98, undoclosetab 7.5.0

![undo](https://user-images.githubusercontent.com/20844322/158281625-f499a930-7db5-4d1e-a915-85e698892d64.png)

**Comment by M-Reimer** [comment]
I seem to have missed that one. Nice to see that you solved your issue.
