### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by juanriccio** [M-Reimer/undoclosetab#109]
This extension (v7.5.0) stopped working. It might have happened on upgrading to Firefox v98.0.2. I've since tried other similar extensions, and none of them will work anymore. However, the Firefox built in list of recently closed tabs (History -> Recently closed tabs) still works fine, and I can pick any tab in the list. (Is it actually built in, or is it generated by Undo Close Tab?)

It might be just my Firefox profile getting corrupted, but I thought it better to report the issue here. If I get more info, I will update.

**Comment by M-Reimer** [comment]
It is, very probably, the common profile corruption. So far I failed to reproduce the issue on my side.

In the last case someone offered me to send the required profile files for debugging but unfortunately it pointed out that he did not run into the common issue and unfortunately this did not help me to debug the issue at the end.

It is very likely that the "sessionstore.js" file in the profile causes this. Please review this file to find out if you can send this to me without exposing any private info. If so, you can find my E-Mail here: https://github.com/M-Reimer

**Comment by juanriccio** [comment]
Thanks for your reply @M-Reimer!

Short: problem magically solved itself.

Long: I wanted to take you on your generous offer to try and examine sessionstore.js, so I went to look for it. I found it only exists when Firefox is closed, and it has a slightly different name because it is in the custom Firefox compressed format. Made a copy of it, located a tool to uncompress it, proceeded to open it, beautify it, and was setting out to delete some sensitive info. Before I was done, I found the extension now works again. Strange. I haven't tried the other similar extensions yet, but my hunch is they will work as well. Temporary sessionstore.jsonlz4 corruption? Hard to believe, since before even reporting the problem here I'd tried closing/reopening the browser multiple times, and even rebooting Windows.

**Comment by juanriccio** [comment]
More details, as I'd promised. Undoclosetab stopping working then getting back to normal is definitely linked to profile corruption of some sorts. This time, something cleared up some parts of sessionstore.jsonlz4, since even without clearing cookies I lost all open logins, some security conscious sites asked me to authorize my machine again etc. I'm glad I didn't lose any important setting. I wish I knew how to perform such a selective clear operation: I haven't done anything special consciously. At any rate, I'm very happy Undoclosedtab works again :-)
