### ISSUE TITLE
Add Support for Manage Extension Shortcuts to allow shortcut to activate an undo

### ISSUE THREAD

**Issue by sleeptil3** [M-Reimer/undoclosetab#115]
Using `commands` in manifest.json and a commands shortcut listener, allow user to activate the undo command using a shortcut.

**Comment by M-Reimer** [comment]
But why? Firefox has a built in shortcut "Ctrl + Shift + T"

**Comment by sleeptil3** [comment]
> But why? Firefox has a built in shortcut "Ctrl + Shift + T"

Well, because it activates _your extension_ and not the built-in undo tab close, which would allow it to use the custom settings set in the extension's configuration. Like the one that will re-open multiple tabs if closed within a certain time limit.

**Comment by M-Reimer** [comment]
Fixed in the upcoming release.
