### ISSUE TITLE
[Feature Suggestion] Increase the entry limit (six) on the last closed tab history pop-up

### ISSUE THREAD

**Issue by caglarkoksal** [M-Reimer/undoclosetab#12]
There are two more functional "undo close tab" add-ons on AMO and both have more than six entries on their respective closed tab history pop-up.

- https://addons.mozilla.org/en-US/firefox/addon/undo-close-tab-button/?src=search
This add-on has ten items on its context menu. This add-on's source code is here: https://github.com/codefisher/toolbar_buttons/tree/master/data/undo-close-tab

- https://addons.mozilla.org/en-US/firefox/addon/undo-closed-tabs-revived/?src=search
This add-on has a limit of 25 items on its context menu. Unfortunately I could not find the source code for this webextentions add-on

I am not a coder myself, so I do not know how hard, if ever, to implement this feature. However, I think your add-on is superior to both in terms of functionality and design, so if this is not possible, no worries. Cheers.

**Comment by yfdyh000** [comment]
They use popup to simulate menus instead of contextMenus API.

**Comment by M-Reimer** [comment]
As @yfdyh000 already wrote, they don't use a context menu.
Seems like the second Addon only offers a popup and no way to "restore by click" at all.
The first one allows to configure this behaviour. You can either have "click to restore last tab" or "click to open popup".
I don't like any of these ways. It's much nicer to be able to restore with left click and get the list with right click. No need to change configuration for that. But with this way, we run into the limitation of 6 items maximum. This is worked around with the "More items" submenu, which is the only way to have more items in the button context menu. So you have the last 5 to 6 closed tabs on top level and older tabs in "More items".
I'm currently preparing a new version which will also have optional context menu entries in the tab bar context menu and the page context menu. Both of them will not have the 6 items limit.
