### ISSUE TITLE
[New addon] Closed tab notifier

### ISSUE THREAD

**Issue by danimesq** [M-Reimer/undoclosetab#120]
Desktop lacks a handy feature mobile browsers have: toast message telling a tab was closed, with a button to undo/restore it.

The same expertise you had with "undoclosetab", is the same experience required for such unexisting addon.

@M-Reimer Are you open for that? =D

**Comment by M-Reimer** [comment]
Are you really sure you want that? At least I am closing tabs all the time and having a notification for every single tab close would pretty soon be very annoying.

- You know that you currently closed a tab
- You can have the button handy in your browser toolbar

So a notification would be just a annoying way of having the same thing you already have.

**Comment by M-Reimer** [comment]
No more feedback so I guess I can close this issue.

**Comment by danimesq** [comment]
Sorry, I was too busy to answer and, also, to remember about this issue.

Thanks for reminding

> Are you really sure you want that?

Yes, a lot.

> At least I am closing tabs all the time and having a notification for every single tab close would pretty soon be very annoying.

I'm my mobile phone it doesn't annoys me; but I guess most of the people at Desktop would feel annoyed and not comfortable like those who are habituated to see that behavior on phone, so such a addon should be naturally opt-in.

> You know that you currently closed a tab

Not my case. I work like an octopus in my computer thinking and clicking quickly in a lot of places in a few seconds, so I would like to be notified of a closed tab in the process (lol) and a button on this notification to restore/reopen the notified tab.
