### ISSUE TITLE
in firefox 113 the toolbar button right click no longer works.

### ISSUE THREAD

**Issue by rezad1393** [M-Reimer/undoclosetab#124]
in firefox 113 the toolbar button right click no longer works.

**Comment by M-Reimer** [comment]
Works great for me. Maybe you ran in a bug which just was fixed with the latest release of my Add-on. Do you still have problems with the context menu?

**Comment by rezad1393** [comment]
I don't know what fixed it but it is fixed. 

it seems your new version even fixed some regression that that sometimes (before this bug) would had to right click the button again to show the list.
thank you.
