### ISSUE TITLE
[Idea] Suggestions to change extension icon

### ISSUE THREAD

**Issue by emvaized** [M-Reimer/undoclosetab#128]
I think it would be cool if extension icon incorporated Firefox built-in [undo icon](resource://gre/chrome/toolkit/skin/classic/global/icons/undo.svg) instead of current circle arrow. It probably would make it blend better in the nav bar and look more minimal.

Here's a quick sketch of my idea — icon preserves current "tab like" shape on bottom, but arrow is detached from it, and is in fact built-in "undo" icon, a little bit skewed and stretched for visual balance: 
![undoclosetab-new](https://github.com/M-Reimer/undoclosetab/assets/37851576/74884909-4310-4964-9f7c-0f2e05d0ac1f) 

I also have a thought that overall "tab" figure on bottom of the icon is no longer relevant, as tabs in Firefox don't look like that for a long time already. Maybe it makes sense to replace it with some kind of rectangle with rounded corners, which would resemble the "tab" a bit more? However, such change may turn out to be too much radical, and result in users not able to find the icon on the navbar.

**Comment by M-Reimer** [comment]
Which version of Firefox does have an "Undo" button? I can't find one.

**Comment by emvaized** [comment]
> Which version of Firefox does have an "Undo" button? I can't find one.

I was referring to the built-in "undo" icon, not button. It is included in every modern version of Firefox, and can be referred by the following URL: 
[chrome://global/skin/icons/undo.svg](chrome://global/skin/icons/undo.svg)

**Comment by M-Reimer** [comment]
Can it be seen anywhere in the Firefox UI?

**Comment by emvaized** [comment]
Not sure. My guess is that it was previously used for text fields context menu

**Comment by M-Reimer** [comment]
If noone can find it anyway, then I would opt for keeping the current icon. It actually was adapted to match theme updates several times in the past, so I think it currently matches pretty well.

**Comment by rr1231234** [comment]
Would love a new icon that has a simpler look like this [addon's](https://addons.mozilla.org/en-US/firefox/addon/zbutton-undo-close-tab/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)

**Comment by Gitoffthelawn** [comment]
@rr1231234 I think there is some (or much) personal preference involved, but when I saw that one, I thought it was a stylized "back" button.

Although I do appreciate the desire for something simpler, I personally like this extension's current icon.

**Comment by M-Reimer** [comment]
There are more serious issues that need dealing. Changing the Add-on icon isn't really a priority in my opinion.
