### ISSUE TITLE
[Idea] keyboard short for using undo close functionality

### ISSUE THREAD

**Issue by pcvvelzen** [M-Reimer/undoclosetab#129]
Having a straightfoward default keyboard shortcut would be a great addition for everyone who also uses CTRL/CMD + W to close a tab, being able to undo the close tab by a default keyboard shortcut like CRTL/CMD + (SHIFT?) + W would make the workflow in Firefox even more smooth.

**Comment by M-Reimer** [comment]
You can define whatever shortcut you like already:
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
And no: I don't want to define a default shortcut. In theory there already is one (Ctrl + Shift + T) as that's what Firefox uses by default.
