### ISSUE TITLE
[Feature Suggestion] Hovering over an URL title shows full url address 

### ISSUE THREAD

**Issue by caglarkoksal** [M-Reimer/undoclosetab#13]

**Comment by M-Reimer** [comment]
The WebExtensions API doesn't allow that. That's all we have:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/create
And to be honest I don't even know if this was possible in the old "XUL based" Firefox API as I don't think that there is any operating system independent way to have "tooltips" on menu items.
