### ISSUE TITLE
Can't find Icon unduclosetab sinds firefox 120.01

### ISSUE THREAD

**Issue by HWH84** [M-Reimer/undoclosetab#133]
Icon is gone, not in toolbar ot taskbar.

**Comment by M-Reimer** [comment]
Check that silly puzzle piece icon, Mozilla has added. And no, unfortunately nothing I can do about. Complain on bugzilla.mozilla.org

**Comment by M-Reimer** [comment]
Actually I found a property by accident which may restore the old behavior. This is definitely something to look into as the whole idea of this add-on is the button. Would be useful to have it right away without manually "pinning" the button.

**Comment by M-Reimer** [comment]
Still silly how Mozilla botched up Add-on toolbar icons by adding the Chrome UI like a foreign body but this at least makes the icon visible directly.
