### ISSUE TITLE
Use Proton folder icon for "More Entries"

### ISSUE THREAD

**Issue by Aleksandra0056** [M-Reimer/undoclosetab#135]
The "More Entries" right-click context menu item uses the old folder icon.

Actual icon on More Entries:
![Old More Entries item icon](https://github.com/M-Reimer/undoclosetab/assets/69351811/ec7a9d18-4696-45e8-ac35-d1cae009cca4)

The icon which should be used:
![folder](https://github.com/M-Reimer/undoclosetab/assets/69351811/a7c8d38c-d1fe-493c-8ed3-14e2232fa0a3)

**Comment by M-Reimer** [comment]
My licensing is incompatible with Firefox's. So I can't copy icons. But I can try to trim the colors a bit to look similar.

**Comment by Aleksandra0056** [comment]
> My licensing is incompatible with Firefox's. So I can't copy icons. But I can try to trim the colors a bit to look similar.

I understand your licencing incompatibility. Do what you think you should.

**Comment by Aleksandra0056** [comment]
By the way, I must say, that your extension is great. I think, that more people should start using it.
