### ISSUE TITLE
The amount setting of closed tab doesn't work

### ISSUE THREAD

**Issue by hdd60311** [M-Reimer/undoclosetab#16]
Using 56beta12, the setting is 25 but it still only shows 20 closed tab.

![1](https://user-images.githubusercontent.com/5089290/30553467-e17916a8-9cd3-11e7-84ba-a784db1b7621.png)
![2](https://user-images.githubusercontent.com/5089290/30553468-e185150c-9cd3-11e7-88e5-5d480cdf307b.jpg)

**Comment by yfdyh000** [comment]
The amount is top menus + more menus.

**Comment by hdd60311** [comment]
This? Still only 20 closed tab.

![default](https://user-images.githubusercontent.com/5089290/30554367-e42fb796-9cd6-11e7-8bcc-fff0e77ed6b3.jpg)

**Comment by jingyu9575** [comment]
Try increasing [`browser.sessionstore.max_tabs_undo`](http://kb.mozillazine.org/Browser.sessionstore.max_tabs_undo) in `about:config`, restart, and close more tabs.

**Comment by M-Reimer** [comment]
I had a closer look at this and I guess what you did is that you closed tabs in two windows. The maximum is 10 tabs per window which results in your 20 tabs.

Increasing the browser.sessionstore.max_tabs_undo preference fixes this. Set this to 25 and you can get the maximum of 25 items even in one window.

I've added some information about this to the AMO page.
