### ISSUE TITLE
Middle click open in background

### ISSUE THREAD

**Issue by Qwash** [M-Reimer/undoclosetab#17]
As in title, Current behavior only allow Lclick to open in foreground

**Comment by M-Reimer** [comment]
There is no way to know that the middle mouse button was used. At least none that I know of. I've filed a bug for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1405031

**Comment by M-Reimer** [comment]
If this API ever gets added, maybe it would also be possible to add a "restore last closed window" feature by, for example, shift + clicking on the button.
