### ISSUE TITLE
Favicons in recently closed context menu

### ISSUE THREAD

**Issue by Mathnerd314** [M-Reimer/undoclosetab#2]
Like [here](https://addons.mozilla.org/en-US/firefox/addon/undo-close-tab-replacement/):
![image](https://cloud.githubusercontent.com/assets/322214/25783683/e1e9f4ec-331d-11e7-9ca0-2807d2c53791.png)

I guess first it needs changes to the WebExtension API, so follow [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1321544).

**Comment by M-Reimer** [comment]
I already follow this bug and yes, this will be added as soon as it is possible.

**Comment by M-Reimer** [comment]
This feature is available in release 3.0.0.
You have to have at least Firefox 56 for this to work!
Thanks to yfdyh000 for his help with this new feature.
