### ISSUE TITLE
Undo latest closed tab with a middle click on the tab bar

### ISSUE THREAD

**Issue by SuperPat45** [M-Reimer/undoclosetab#23]
Currently when you middle click on the tab bar, a new tab is opened.
Is this behavior may be changed to open intsead the latest closed tab as allowed by tabmixplus.

**Comment by M-Reimer** [comment]
I think this is not possible with the current API state and I don't know how far Mozilla will go when it comes to overriding browser default behaviour.

**Comment by Qwash** [comment]
Hello @SuperPat45 
you can undo last closed tab with a middle click at the screen topmost right corner using [Autohotkey](https://autohotkey.com)

```
#IF WinActive("ahk_exe " "firefox.exe")
	~Mbutton::
		CoordMode, Mouse, Screen  
		MouseGetPos, Xpos, Ypos 
		IF (Xpos = A_Screenwidth-1 And Ypos = 0)
			{
			Send ^+{T}
			}
		Xpos=  ;Free the memory
		Ypos=  
	Return
#IF WinActive
Return
```

**Comment by M-Reimer** [comment]
Even if it would be possible, I think this would be a task for some special addon which just does the "middle click on tab bar" thing. It is never a good idea to put too much features in one addon.

**Comment by khari3** [comment]
Sir,

Will you add this now

**Comment by M-Reimer** [comment]
No.
Still no API for this (which makes it technically impossible)
