### ISSUE TITLE
Use Photon colors for icons

### ISSUE THREAD

**Issue by rugk** [M-Reimer/undoclosetab#29]
It would be nice if you could use the [Photon colors](https://design.firefox.com/photon/visuals/color.html#icons-and-other-elements) for the icons, so they match the rest of Firefox' design.

**Comment by M-Reimer** [comment]
Thanks for the information. Didn't know about this one and the color, so far, was based on a screenshot taken from the Firefox window.

**Comment by rugk** [comment]
As far as I see, you did not use the transparency of the color. Actually that is totally possible (and recommend) in the SVg though!

**Comment by M-Reimer** [comment]
I did.
It is not possible in the "color" directly.
And it is not possible in the individual elements either as I have two overlapping items.
So I had to group the two and add the opacity value to the group:
https://github.com/M-Reimer/undoclosetab/blob/master/icons/undoclosetab.svg?short_path=5292d4f#L55

**Comment by rugk** [comment]
Ah, okay… BTW you could also use https://jakearchibald.github.io/svgomg/ for minifying the SVG.

**Comment by M-Reimer** [comment]
I don't think a few extra bytes are a problem. Dropping them may result in problems when editing again.
If this would really result in any advantages, I could create a Makefile rule to create a minified version based on the version, I use for editing, but I don't think it's worth the trouble.

**Comment by rugk** [comment]
Of course you need to keep the old version. :smile: 

A different 8though not so hardly optimized way) is to save the SVG as "Optimized SVG" in Inkscape.

**Comment by M-Reimer** [comment]
IMHO it is nice and handy that Firefox opens the file, I use for editing, directly.

If it would really result in any noticeable improvement, I would definitively add some optimization. Most probably just in form of some more "sed" rules in the Makefile to drop or simplify some stuff.
