### ISSUE TITLE
Ceased functioning at FF Nightly 63.0a1

### ISSUE THREAD

**Issue by anastrophe** [M-Reimer/undoclosetab#30]
Just fyi. Undo close tab has ceased functioning since most recent Nightly update (or possibly one or two revs back, hard to nail down). 

<insert sad face>

**Comment by anastrophe** [comment]
Thanks for the reply. It does work if I use a new blank profile. Is there anything short of a starting over with a new profile that I can do to fix this? I've got years and years of customizations, naturally.

**Comment by M-Reimer** [comment]
You can try to reset parts by deleting files in profile.

As far as I know Nightly got a new storage format for Addon settings.

In your profile you may find a directory "browser-extension-data". Maybe rename this one to reset all Addon settings to default.

The problem may reoccur if you use the same profile for Nightly and stable Firefox and switch between them. Don't do that.
