### ISSUE TITLE
Feature request: add an option for clicking to show recent closed tabs

### ISSUE THREAD

**Issue by kidwm** [M-Reimer/undoclosetab#31]
instead of restoring the last closed tab.

or offer an option to swap left and right click functions.

**Comment by M-Reimer** [comment]
This is not possible. Context-Menu is "right click". Nothing I could do about this.

**Comment by rpayanm** [comment]
Can you do like [Undo Closed Tabs Button (revived)](https://addons.mozilla.org/en-US/firefox/addon/undo-closed-tabs-revived/) does?

**Comment by M-Reimer** [comment]
No, as this Addon **only** has the "menu list". It is bound to the "browserAction" as "popup" and the documentation says:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/onClicked
> This event will not fire if the browser action has a popup.

This means that you can't get a "single click restore of last tab" with this Addon. Just not possible as they use the only "single click" event (which is left click) to pop up their menu.

With my solution I can have both. I can make use of the "onClicked" event handler for my "single click restore" and place the menu to the tab list into the context menu.

**Comment by rpayanm** [comment]
ok, thank you!
