### ISSUE TITLE
Just remember the 10 last tabs

### ISSUE THREAD

**Issue by adocampo** [M-Reimer/undoclosetab#33]
Even I have the 25 limit on closed tabs, the extension just remember the 10 latest closed tabs.
I would love to the extension to remember not just 25, but unlimited (or lets say at least the latest 100 closed tabs).
Undo closing tab with default firefox behavior (e.g.: Ctrl + Shift + T) works just as expected, and I can restore all the tabs since the last launch of the browser.
I disabled all other addons to see if any of them was interfering. No luck
OS: Arch Linux
Firefox: All versions since 57+

**Comment by M-Reimer** [comment]
I have some information about this on addons.mozilla.org:
https://addons.mozilla.org/en-US/firefox/addon/undoclosetabbutton/
See "About this extension" and scroll down up to "Please note". Relevant is the second point.

**Comment by adocampo** [comment]
Yes, with this I can reach the limit of 25. Thank you! 
I also modified the max tabs on about:config up to 100, but extension cannot undo more than 25. It will be possible or there are some kind of limitation for extensions?

**Comment by M-Reimer** [comment]
This is also answered in the "Please note" section :yum: 
But here again the link to developer.mozilla.org:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/MAX_SESSION_RESULTS

> It is read-only for WebExtension code, and is set to 25.

I'm already maxing out the spec.

**Comment by jingyu9575** [comment]
I see different results here. On my Firefox 63.0.1 / Windows 10, I modified the about:config entry to 100, and then force to set the extension option to 100 by increasing the HTML attribute `max="25"`. As in the screenshot, the extension can go beyond the limitation.

![default](https://user-images.githubusercontent.com/8923139/47958363-3268fe00-e005-11e8-97f7-015aa63a35d4.png)

**Comment by jingyu9575** [comment]
@M-Reimer I opened options.html and used the developer tools to increase the `max` attribute of this element:
```HTML
<input type="number" id="number_inputbox" min="1" style="width: 6em" title="..." max="25">
```
so the UI limitation was removed and I could put 100 in the extension's storage. After this the extension would show more items.

---

I put a breakpoint on that line and it said `this.MAX_SESSION_RESULTS` is undefined, which causes the limitation [ineffective](https://dxr.mozilla.org/mozilla-central/source/browser/components/extensions/parent/ext-sessions.js#40). Perhaps it is a bug. (I hope they will not notice it...)

**Comment by M-Reimer** [comment]
> I put a breakpoint on that line and it said `this.MAX_SESSION_RESULTS` is undefined, which causes the limitation [ineffective](https://dxr.mozilla.org/mozilla-central/source/browser/components/extensions/parent/ext-sessions.js#40). Perhaps it is a bug. (I hope they will not notice it...)
> 
> Explicitly giving a larger number does not work as there is limitation in the schema JSON.

I guess it will be noticed at some point and I don't want to base a "feature" in my extension on a Mozilla bug. I've searched Bugzilla for possible bug reports and found this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1392125

So there is some chance that they'll just drop the limitation. We'll see what happens. Will leave this one open until the Mozilla bug gets resolved in some way.

**Comment by moreaki** [comment]
There appears to be a preliminary patch upstream (https://phabricator.services.mozilla.com/D168824) to alleviate that limit and bug regarding `MAX_SESSION_RESULTS` being undefined, but somehow nobody is taking care of it.
