### ISSUE TITLE
Reopen last closed tab on right-click menu

### ISSUE THREAD

**Issue by feierfrosch** [M-Reimer/undoclosetab#34]
Hello,

is it possible to add a function to the right-click menu that doesn't give me the list of the last closed tabs, but simply re-opens the last closed one? I used to rightclick and press G (_G_eschlossenen Tab wiederherstellen) in quick succession on the old FF, but that funcionality apparently was added by TMP which is not available for the new one.

**Comment by M-Reimer** [comment]
Thanks for adding this as issue.

I think this could be a great new feature.

This would have to be added as another optional menu item, but "interlocked" with the existing option (each Addon can only add one submenu item).

**BUT** the first implementation would most probably not have the access key ("G" in your example) as this is only possible in Firefox 63 and I have to be compatible down to at least Firefox 60.

**Comment by M-Reimer** [comment]
Fixed in 4.3.0.
"Access keys" are not possible in Firefox 62, which is the current "stable" Firefox release.
If you really need this, please create a follow-up issue.

**Comment by feierfrosch** [comment]
I have no idea what "access keys" are. When I right-click right now and press "G", it opens the dropdown list of closed tabs (using the current version of your extension in German). So why is it not possible to set this behaviour to open the last closed tab? I don't understand why Mozilla had to change that and make it (at some parts: way!) worse than it was before -.-'

**Comment by M-Reimer** [comment]
You are right. So this issue is resolved.

"Access keys" would be underlined in the context menu. I didn't know that I can just use the first character of the menu item label. So adding this "accesskey" feature would just be a cosmetic change and not needed to get the actual functionality.
