### ISSUE TITLE
Context menu (recently closed tab list) on toolbar button missing in full-screen mode (F11)

### ISSUE THREAD

**Issue by M-Reimer** [M-Reimer/undoclosetab#35]
--> Upstream Bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1494028

**Comment by C-McButterpants** [comment]
Sorry Manuel, ofc you're right, very silly to try and exchange info in a review section... lol

![2018-10-01 20_06_25-context menu recently closed tab list on toolbar button missing in full-screen](https://user-images.githubusercontent.com/26235926/46310898-8c1a7a80-c5b8-11e8-8832-c4d7112d9877.png)

**Comment by Anach** [comment]
I have the same issue, however, it's not just fullscreen mode, the icon is simply missing any functionality. It only gives me the standard toolbar context menu when right-clicked, and does nothing at all when left-clicked. This started with a recent update a few days ago.

**Comment by M-Reimer** [comment]
The issue has been accepted upstream.
Now we have to wait for the official fix for this issue.

**Comment by jacktose** [comment]
For anyone interested in fixing this issue, I recommend voting on [the Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1494028).

![bug vote](https://user-images.githubusercontent.com/12414794/61179430-f84df400-a5b6-11e9-840c-bee5820d878f.png)

**Comment by M-Reimer** [comment]
Can someone here retest if this is fixed in Windows, too. I can't test there but I just did a test on my system (Linux) and the bug seems to be gone.

**Comment by Dystopian** [comment]
> Can someone here retest if this is fixed in Windows

I checked in windows and the button works in full-screen mode.

**Comment by M-Reimer** [comment]
> > Can someone here retest if this is fixed in Windows
> 
> I checked in windows and the button works in full-screen mode.

Thanks for checking
