### ISSUE TITLE
Icons not properly visible on some static themes

### ISSUE THREAD

**Issue by M-Reimer** [M-Reimer/undoclosetab#36]
I did some tries with several themes on AMO and with some of the them the icon is difficult to see.

There seems to be a difference between the original icons and the icon I use.

Seems like Mozilla either doesn't make their icons 80% opaque or they switch to 100% opacity for some themes.

Will investigate this further, but it seems like the easiest fix is to make my icon 100% opaque, too.

**Comment by M-Reimer** [comment]
Removing transparency is only one issue.
The major problem is that I don't get notified about the theme change at all.
--> Upstream bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1494620

**Comment by rugk** [comment]
Hmm… why do you even manually handle theme changes?

These two lines should do it all, AFAIK:
https://github.com/M-Reimer/undoclosetab/blob/master/manifest.json#L29-L30

Firefox automatically determines whether the theme is black or white and switches to the appropriate icon. (unless you overwrite that via JS, of course)

**Comment by rugk** [comment]
Well… of the correct color is not correctly detected then this is an issue of Firefox.
But you well likely always have themes that may have a light "edge" where your icon symbol is and are otherwise pretty dark. I see nothing you can do here, as an add-on author.

**Comment by rugk** [comment]
A thing like https://discourse.mozilla.org/t/use-theme-colors-for-svg-favicons/29165 would likely fix the problem properly…

**Comment by M-Reimer** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1492145 has been accepted.
I really hope they'll also cover "static themes" with their fix.

**Comment by geniuszxy** [comment]
@M-Reimer a part of the icon disappears since upgrade Firefox to 65.0 if I use a custom theme.
![q1](https://user-images.githubusercontent.com/2471200/52531633-25218500-2d53-11e9-8158-d36cfe1a8217.PNG)
ThemeUpdated is invoked, but the output seems lost some data.
.

**Comment by M-Reimer** [comment]
Interesting. Please also add a link to the theme (addons.mozilla.org link).

**Comment by M-Reimer** [comment]
Did a short test with "Firefox Color" (my common testcase for dynamic themes) and it works there.
I really need the theme and maybe this is a "Windows only" problem which I couldn't debug at all...

**Comment by geniuszxy** [comment]
@M-Reimer , the icon works well with Firefox Color, my problem is occured with static themes, such as this one: https://addons.mozilla.org/en-US/firefox/addon/modern-sunstet-v2/?src=search

**Comment by M-Reimer** [comment]
Fixed:
https://github.com/M-Reimer/undoclosetab/commit/140187a308b74ffd6807ac2d89c8ec6dbb282f8a

**Comment by Henry47a** [comment]
Since my favorite theme [Dark Fox No Logo](https://addons.mozilla.org/de/firefox/addon/dark-fox-no-logo/) got an update yesterday, the undoclosetab icon is no longer displayed correctly.

I made some tests with the theme on Windows 7 and Firefox 66.0.5 (64-bit)

With theme version 2.0 and undoclosetab 4.4.3 only a black arrow is displayed.
With theme version 1.0 and undoclosetab 4.4.3 the icon is displayed correctly.
With theme version 2.0 and undoclosetab 4.1.3 the icon is also displayed correctly.

**Comment by M-Reimer** [comment]
Thanks for reporting. This is another missing color name which has to be checked on theme update. Fixed by https://github.com/M-Reimer/undoclosetab/commit/d806125745a69a7bc13b4516d255940669718e3b
Will be part of the next release.

**Comment by M-Reimer** [comment]
I've published 4.4.4 with another fix. In this case I not only added all possible color names that seem to influence the icon color but I also added a fallback to not re-render the icon if no usable color at all can be found in the used theme.

If there are other themes with problems, then please open a new Issue and add a link to the problematic theme.

**Comment by M-Reimer** [comment]
I've published 4.4.4 with another fix. In this case I not only added all possible color names that seem to influence the icon color but I also added a fallback to not re-render the icon if no usable color at all can be found in the used theme.

If there are other themes with problems, then please open a new Issue and add a link to the problematic theme.
