### ISSUE TITLE
The icon is higher than other browser icons

### ISSUE THREAD

**Issue by jingyu9575** [M-Reimer/undoclosetab#4]
See the screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/8923139/26281258/6d111276-3de1-11e7-8197-79ab7377ff94.png)

I suggest setting the icons' size to squares (width=height) and centering the content.

Use these icons:

![undoclosetab](https://cloud.githubusercontent.com/assets/8923139/26281233/c8899750-3de0-11e7-8a5d-8a29128e1cf9.png) ![undoclosetab 2x](https://cloud.githubusercontent.com/assets/8923139/26281234/d09f0cfe-3de0-11e7-9bee-39f13e7c9a9e.png)

Result:

![result](https://cloud.githubusercontent.com/assets/8923139/26281266/9d3a9fda-3de1-11e7-9f27-a6127878ddde.png)

**Comment by M-Reimer** [comment]
Thanks for reporting.
Seems like 18x18 is the size, used by Mozilla, too.
But as far as I could find out, the "big size" is 36x36.
Updated buttons will be added to the next release.

**Comment by M-Reimer** [comment]
I've added a new icon which should fit better between the new Mozilla icons.
