### ISSUE TITLE
Not work in Firefox 66?

### ISSUE THREAD

**Issue by pro100Hub** [M-Reimer/undoclosetab#48]
Not work in Firefox 66?

**Comment by M-Reimer** [comment]
Absolutely no problems here.
What's exactly your problem?
Try a reinstallation, please.

**Comment by pro100Hub** [comment]
@M-Reimer 
After upgrading from 65.0.2 to 66, my user profile broke down. Reinstalling the add-on did not help. I had to create a new user, now everything is in fine.
Issue closed.

Thanks. :+1:

**Comment by M-Reimer** [comment]
Really great that Mozilla still has this problem of profiles getting corrupted.
Thanks for your feedback!
