### ISSUE TITLE
Not works on Firefox 67.0b9

### ISSUE THREAD

**Issue by aisen0921** [M-Reimer/undoclosetab#49]
And my undoclosetab version is newest.

**Comment by M-Reimer** [comment]
Impossible to reproduce.
I checked with a "Nightly build" first without issues.
Just to be sure, I downloaded 67.0b9 and checked with this. No issue again.
Please try reinstalling or (as the Beta profile seems to be separate from the main one anyway) with a new profile.

**Comment by aisen0921** [comment]
I try reinstalling and it's work! thanks a lot!
