### ISSUE TITLE
Not Working on FF66.0.3 on Mac 10.11 

### ISSUE THREAD

**Issue by M-Reimer** [M-Reimer/undoclosetab#50]
Hi @githubNikK
Seems like you are new to github. I'm moving your Issue, you accidentally created as commit to a fork, to here.

`Hi Guys, I recently DL'd UCT, and although all the reviews are great, for some reason, it is not working. Ihave tried it over the last ffew days and my last tab closed does not re-open. Any assistance would be greatly appreciated. I am working on Mac 10.11.6 on FF66.0.3. All updated. Let me know further. Cheers.`

**Comment by M-Reimer** [comment]
As I absolutely have no experience with Mac OS, it would help me if:
- Someone else can tell me if he uses undoclosetab successfully on Mac?
- @githubNikK could create a fresh profile in his Firefox (search for "profile manager". You can create a second profile next to your current one without loosing anything) just to be sure that everything works in a virgin profile.

**Comment by francwalter** [comment]
I am on FF 61.0.2 (64-Bit) on Mac OS 10.11.6, because of some important Add-Ons. This one worked till today (I noticed it today).
This Add-On is now in the list of unsopported Add-Ons, among some other till recently working Add-Ons (e.g. uBlock origin).
What happened?

**Comment by M-Reimer** [comment]
You are right. This was a big problem that happened on all operating systems. I also had this problem on Linux.

**Comment by francwalter** [comment]
As I am stuck on Firefox 61 (I need the bookmarks-description in the bookmarks Library), there seems no solution for it.
Firefox is one of the few applications I use, that became (at least for me) with its development less and less usable (breaking features/Add-Ons which made me use FF). 
Its not development, but envelopment ;)

**Comment by M-Reimer** [comment]
What exactly do you need there? Maybe you can contact me via private mail about this: mail <at> m-reimer (dot) de
If you can convince me that this is a nice feature, it may be one of my future projects.

**Comment by M-Reimer** [comment]
No answer from @githubNikK since several weeks --> Closing for now.
Please answer if the problem still exists.
