### ISSUE TITLE
List of recently closed tabs is blank if a JPG link happened to get closed

### ISSUE THREAD

**Issue by daishi424** [M-Reimer/undoclosetab#52]
Hello Manuel! 

Got a weird bug here that is voiding my closed tabs list.

Steps to reproduce:

1. Install v. 4.5.0.
1. Close several tabs with web pages
1. Ensure that list of resently closed tabs in the context menu is populated with above tabs
1. Close a tab where a JPG file link is opened

Bug: 
- List of recently closed tabs is suddenly blank
- A list is left blank until you restore that last closed JPG tab

OS: Windows 10 1809, Firefox 67.0.1

P.S. I'm enjoying this addon immensely! Installing v.4.4.4 until this issue is fixed.

**Comment by galenhuntington** [comment]
I'm having a similar problem, but what seems to trigger it is a tab with a `file:///` URL.  If I close it, the menu is blank till I restore it.

**Comment by M-Reimer** [comment]
I think I know why this happens.
Neither the JPEG nor the file:// has a favicon. So I have two options: Don't display an icon or use some kind of "default icon".
Mozilla uses a default icon in this case which is something like a simplified globe. I think I'll just replicate this.

**Comment by M-Reimer** [comment]
Fixed and 4.5.1 is on its way

**Comment by M-Reimer** [comment]
BTW: It's ugly that there was **no** error in web console whatsoever. Mozilla and its ugly WebExtensions bugs...
