### ISSUE TITLE
[Suggestion] Displaying the full address when hovering over the link

### ISSUE THREAD

**Issue by pro100Hub** [M-Reimer/undoclosetab#54]
Hello.
Please add the ability to view the full address when you hover over the link. At the moment, only the title is visible, but the function of viewing the address of this link is lacking.

Regards.

**Comment by M-Reimer** [comment]
Seems to be a good idea.
But not possible so far.
I've created an upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1559082

**Comment by M-Reimer** [comment]
We won't get API for this. All complaints go to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1559082

**Comment by pro100Hub** [comment]
@M-Reimer 
Is it possible to use the function that works by default in Bookmarks? There in tooltip shows the address. Can this function be used in your add-on?

**Comment by M-Reimer** [comment]
No. That's what I requested. It got declined.

**Comment by Yaron10** [comment]
Would it be possible to display the address in the status bar?

**Comment by M-Reimer** [comment]
No, because
a) There is no such a thing as a "status bar" any more in Firefox
b) Even if there would, I wouldn't be able to find out that someone hovers the mouse over my menu entries as there is no API for that.

Again: All complaints to: https://bugzilla.mozilla.org/show_bug.cgi?id=1559082

**Comment by Yaron10** [comment]
:+1:
