### ISSUE TITLE
Does not work on mobile

### ISSUE THREAD

**Issue by Marco-Sulla** [M-Reimer/undoclosetab#59]
I installed this extension on Firefox Mobile. Well, it does not work. It displays an annoying bottom tab only when the tab is closed to restore it, and it disappear quickly. When I click on the "Restore tab" menu, it does nothing.

I'm using Firefox mobile (Fennec) 68.0 on Android 7.0 kernel 4.1.18-ga01d40c, on a Honor 6x BLN-L21 with EMUI 5.0.1

**Comment by M-Reimer** [comment]
Can't work as API is missing. It is also not marked as Android compatible so you shouldn't find it when searching on AMO

**Comment by Marco-Sulla** [comment]
Can't you play with History?

**Comment by M-Reimer** [comment]
This is just an history but no real session. So restoring is not possible. Just reopening including reloading. And I don't think I can get access to this "recently closed" status. But I'll check that.

And: You are right: Addon is listed for Android.

Will check both

**Comment by M-Reimer** [comment]
The Addon is not listed as being Android compatible. So it's not my fault that it is listed.

I had a look at the API documentation and I don't have access to the history from the Android version of Firefox.

But: I have access to some parts of the tab API which may allow to hack something together. I'll do some tests with that.

**Comment by M-Reimer** [comment]
**May** be possible to at least get some "hack" working to somewhat "fake" being able to restore tabs. But I'm not 100% sure so far.

**Comment by Marco-Sulla** [comment]
Well, when you close a tab, Firefox displays you an annoying message Undo for some seconds. So I suppose in the moment you close the tab you can know the closed tab a store it somewhere.

**Comment by M-Reimer** [comment]
Yes, I can. The only thing I currently don't like is that there is some undo close tab support built already into Firefox on Android. You can get it by opening a new tab, then choosing history and there "recently closed". My workaround solution would not interact with that. Meaning that restoring a tab with my solution would not remove the tab from this list.

**Comment by M-Reimer** [comment]
Fixed in 5.0.0.
Brings **elementary** support with workarounds for missing API.

**Comment by Marco-Sulla** [comment]
\,,/(^_^)\,,/

**Comment by M-Reimer** [comment]
No. I can't. No API to remove this

**Comment by Marco-Sulla** [comment]
Thank you again, I hope FX Mobile devs will implement this as default :)
