### ISSUE TITLE
[feature] custom context menu with options and list

### ISSUE THREAD

**Issue by despecial** [M-Reimer/undoclosetab#63]
Any chance to get your functions and and a context menu like this one combined?
https://addons.mozilla.org/en-US/firefox/addon/undo-closed-tabs-revived/

It has a list on left click with several options, including a feature to open all tabs at once.
The list view looks "better" than a context menu where some entries are hidden.

imo a perfect solution would be:
- single left click: open last tab
- double click or right click: show list with X entries, option to open all tabs or remove them

**Comment by M-Reimer** [comment]
This has been requested several times. The reason why my addon is done the way it's done is, that API is missing or limited.

Currently the only way to have both, some kind of easily accessible list and restore with just one click, is to make use of the "onClick" event (which rules out having a popup) and moving the list stuff to the context menu.
