### ISSUE TITLE
Icon color is the same for all windows, even if they have different themes

### ISSUE THREAD

**Issue by reembar** [M-Reimer/undoclosetab#65]
I use the extension Private Browsing Theme to distinguish the private windows from the normal ones by applying a dark theme to the private windows only.
Undo Close Tab extension set the icon color according to the last opened window, so if I use both normal and private windows at the same time, on one of them the icon won't be visible, as the normal windows has a light theme and the private windows a dark theme.
My suggestion is to set the icon color per window and not for all windows.

**Comment by M-Reimer** [comment]
I'll have a look at this.
I think it may be related to a fix I did for the Firefox ESR version. If I add icon colors per window, it breaks for ESR. But it should be possible to work around this problem by checking the Firefox version.

**Comment by reembar** [comment]
Thanks for answering and for your extension!
If it's any help, here is a simple extension were the icon's color per window works good for me:
Simple Close Tab button
https://addons.mozilla.org/en-US/firefox/addon/simple-close-tab-button/

**Comment by M-Reimer** [comment]
This extension doesn't have "dynamic colors".
Try https://color.firefox.com/ and you see what I mean.
Creating Addons with icons that fit into the existing UI is very difficult as Mozilla has not created simple API for this, so far.

**Comment by M-Reimer** [comment]
Try latest release. Should work there
