### ISSUE TITLE
[SUGGESTION] Keyboard Shortcut

### ISSUE THREAD

**Issue by cansurmeli** [M-Reimer/undoclosetab#66]
Hello.

I'm thinking that it would be nice to have a keyboard shortcut for this add-on; e.g. `CMD + Z` by default.

Safari has this option(both the plug-in functionality and the shortcut for it) by default and it's pretty useful.

As my hands are mostly on the keyboard, I can easily bring up the previous page I closed in an instant compared to grabbing the mouse/trackpad and looking for the button which is a much longer endeavour.

Thanks.

**Comment by M-Reimer** [comment]
Firefox has a keyboard shortcut built in.
It is "Ctrl + Shift + T".
And "Ctrl + Z" is gone anyway. It is registered by Firefox itself for "Undo" and can't be registered by Addons.

**Comment by M-Reimer** [comment]
If all you need is a shortcut, in fact you wouldn't need my Addon at all. Just use the Firefox built in shortcut.

**Comment by cansurmeli** [comment]
Interesting. Before coming to your add-on, I searched a lot for a shortcut of such kind and wasn't able to find one.

Thanks for your insight.
