### ISSUE TITLE
[Feature Request]Add url to list when a page is navigated to another website.

### ISSUE THREAD

**Issue by heroboy** [M-Reimer/undoclosetab#68]
1. When user enter the url in navigate bar, it is just like user want to close the page.
2. Or user click a link, that navigate to another very different url.

**Comment by M-Reimer** [comment]
In my opinion the "Back" button already solves this

**Comment by heroboy** [comment]
1. open a page, then visite website A -> B, close it
2. open a page, then visite website C -> D, close it
In the undo close list there was B and D. I just remember the website A's title, but I don't remember which page(B,D) that has the A in his 'back' list.

**Comment by heroboy** [comment]
So maybe you can make a two level menu. The sub menu of each one is the back history of the page.

**Comment by M-Reimer** [comment]
You have the back history in the back button. I'm currently on my mobile so I can't check but please try long pressing the back button.

**Comment by heroboy** [comment]
@M-Reimer No, you didn't understand me. I know I can right click the back button to popup the history menu. 
But the page was already closed, and I didn't known which page I should undo close to find the website in the back button history.

**Comment by heroboy** [comment]
Or maybe there are many pages, which page's back button I should click to find the 'closed' website?

**Comment by M-Reimer** [comment]
In this case the right tool is the browser history.
Shortcut: Ctrl + H

**Comment by heroboy** [comment]
My English is not good. I don't want to argue with you about all these workarounds. This extension is to make convenient, not add a feature that not exists in the browser itself. 
When I want a URL that I *just* visited but the page was closed, I always want to find it in your undo close button. But I can't find it when it is in the history. So this is why I want this feature is in your extension. If you think this feature is not suitable for the extension, feel free to close the issue.

**Comment by M-Reimer** [comment]
Your English is very good.
I just wanted to show that there are better ways of getting the information you want.
I can't think of any way to add something like this in a way where the feature would really provide something useful.

Your initial thought (add URL's to lists while browsing away from a page) would add too much information. The information, this whole addon is about (closed tabs) would disappear between history stuff.

Adding a second layer would still make using the addon more uncomfortable (two clicks to restore tab) and finding the page, you really want to restore, would require you to go manually through all those submenus. This is also the reason why I think the history serves your need better. It provides fast overview of all pages you visited.

And finally: There is no API to retrieve the information about a closed tab's history. Maybe it would be possible to hack something together (maintaining my own history inside my addon) but that's way too much trouble for a feature most people would keep disabled anyway
