### ISSUE TITLE
Funktioniert nicht mit FF71

### ISSUE THREAD

**Issue by ulli5** [M-Reimer/undoclosetab#70]
Vorige Sitzung wiederherstellen war bei mir schon deaktiviert. Zur Sicherheit habe ich es aktiviert, Neustart, deaktiviert, Neustart. Der Fehler ist noch da.

**Comment by ulli5** [comment]
![2020-01-06 13_56_46-Browser-Konsole](https://user-images.githubusercontent.com/9401837/71819652-d4163000-308c-11ea-8797-8f792818b797.png)

**Comment by ulli5** [comment]
![2020-01-06 14_04_50-Browser-Konsole](https://user-images.githubusercontent.com/9401837/71819954-d927af00-308d-11ea-99ab-6a1d28d2b133.png)

**Comment by M-Reimer** [comment]
Geht wieder?
Was war die Ursache oder Lösung?

**Comment by ulli5** [comment]
Nein, es geht nicht. Ich habe gehofft, dass die Bilder von der Konsole weiterhelfen.
Kann ich etwas tun, um bei der Fehlersuche zu helfen?

**Comment by M-Reimer** [comment]
Keine der Meldungen kommt von meinem Addon.
Bei mir gibt es weder "common.js" noch "h0-main.js".
Bitte versuchen zunächst alle Addons zu deaktivieren. Läuft "Undo Close Tab" dann?

**Comment by ulli5** [comment]
Das Deaktivieren der anderen Addons hat nicht geholfen. Mit einem neu angelegten Profil geht es aber. Ich werde das neue Profil jetzt nach und nach wie das alte einrichten.
