### ISSUE TITLE
(version 6.0.0) Does not seem to be working after a recent update

### ISSUE THREAD

**Issue by ziffusion** [M-Reimer/undoclosetab#72]
Undo Closed Tabs version 6.0.0
Firefox version 77.0.1 (Windows 10)

Clicking on the icon does not restore a closed tab.

The context menu doesn't show up when right clicked.

**Comment by M-Reimer** [comment]
Works for me (Firefox 77.0.1 on Linux).
Did you use version 6.0.0 before (before updating to 77.0.1)?

Please use the shortcut "Ctrl + Shift + J" to open the browser console. Then click the gear on the top right corner and enable "Show Content Messages". Now check the list for errors. Please do this directly after opening Firefox as errors from websites also get logged here.

If this does not help, please follow the following instructions:
https://github.com/M-Reimer/undoclosetab/wiki/How-to-fix-broken-browser-session

**Comment by ziffusion** [comment]
Thanks! That fixed it.

**Comment by M-Reimer** [comment]
Would still be interesting if you used 6.0.0 in an earlier Firefox release.

My hope was that this session corruption thing may have been fixed with version 6.0.0 also...

**Comment by ziffusion** [comment]
This is the first time it has happened to me. I've been using the extension for ages.

Thanks for the great extension (and your help).
