### ISSUE TITLE
addon doesn't work on Firefox 80, Windows 10 x64

### ISSUE THREAD

**Issue by v3470** [M-Reimer/undoclosetab#77]
Tried to click the addon icon but it does not react to the click.

Firefox version: 80.0.1

Windows 10 enterprise edition, version: 10.0.19041.450

**Comment by M-Reimer** [comment]
Can you please try at first:
https://github.com/M-Reimer/undoclosetab/wiki/How-to-fix-broken-browser-session

**Comment by v3470** [comment]
got it. I think that's the reason cause this problem.
