### ISSUE TITLE
Extension not working on Windows  83.0 Firefox Release  November 17, 2020

### ISSUE THREAD

**Issue by ziffusion** [M-Reimer/undoclosetab#87]
Extension not working on Windows  83.0 Firefox Release  November 17, 2020.

**Comment by Hiromacu** [comment]
I think the problem is in your system, because this add-on is working on mine (Win10, Firefox 83.00 (64 bit)). Maybe an other extension cause your issue.

**Comment by M-Reimer** [comment]
Please at first try:
https://github.com/M-Reimer/undoclosetab/wiki/How-to-fix-broken-browser-session

**Comment by ziffusion** [comment]
> 
> 
> Please at first try:
> https://github.com/M-Reimer/undoclosetab/wiki/How-to-fix-broken-browser-session

That worked. Thanks!
