### ISSUE TITLE
[ideas] New icon to fit the firefox proton theme

### ISSUE THREAD

**Issue by Tomharross** [M-Reimer/undoclosetab#91]
The icon does not fit the new proton theme as can be seen in nightly. Perhaps thinner lines would be more fitting. 

https://ibb.co/Jms857w

**Comment by M-Reimer** [comment]
Actually on Linux the theme still looks the way it always looked. Which OS is this? And how did you get the icons that big?

**Comment by Tomharross** [comment]
This was on openSUSE, but it's also true for mac and windows. I was showing firefox nightly, so it's in beta at the moment, but will be released next month, so I guess it's not too much of an issue until then: https://news.itsfoss.com/firefox-proton-redesign/

**Comment by M-Reimer** [comment]
Forgot to close this one. The latest version comes with an updated icon.
