### ISSUE TITLE
"More Entries"

### ISSUE THREAD

**Issue by alexolog** [M-Reimer/undoclosetab#93]
The addon page says:
"If there are more than 6 items in the "last closed tab history", then a submenu "More items" is created. This is to workaround a technical limitation of the WebExtension API."

And yet, a similar addon ([Undo Closed Tabs Button](https://addons.mozilla.org/en-US/firefox/addon/undo-closed-tabs-revived/)) does not have this limitation.

**Comment by M-Reimer** [comment]
Basically the same as: https://github.com/M-Reimer/undoclosetab/wiki/Frequently-Asked-Questions-(FAQ)

My top priority feature is the possibility to have both: One-click restore and the menu.
And the way I've done it is the only way that works with the limitations of the Firefox Add-on API.
