### ISSUE TITLE
Recently close on page context menu

### ISSUE THREAD

**Issue by nollinvoyd** [M-Reimer/undoclosetab#95]
Firefox 89.01

"Recently closed" still appears on my page context menu even though I have that item unchecked in settings.

![Recently closed](https://user-images.githubusercontent.com/20844322/122685832-be35f580-d1c2-11eb-97d6-d1090a75f210.png)

**Comment by M-Reimer** [comment]
Sorry, but I can't reproduce this one. Did a browser restart fix this issue?

**Comment by M-Reimer** [comment]
No more feedback --> Closing.
Please comment if the issue still exists and give a bit more details so I can reopen the issue.
