### ISSUE TITLE
Ampersands(&) in page title are converted to underscores(_) in closed tabs list

### ISSUE THREAD

**Issue by Fanolian** [M-Reimer/undoclosetab#96]
### Steps to reproduce
1. Install Undo Close Tab in a new profile.
2. Open https://en.wikipedia.org/wiki/Procter_%26_Gamble.
3. Close that tab.
4. Check the page title in the extension's recently closed tab list.

### Actual result
Page title becomes `Procter_ Gamble - Wikipedia`.

### Expected result
Page title should be `Procter & Gamble - Wikipedia`.

### Notes
I understand that ampersand can be used to underline a character, but that should not be used in this case.

### System info
Windows 10 21H1
Firefox 89.0.2 or latest Nightly (2021-07-07)
Undo Close Tab 7.2.0

Thank you for your extension.

**Comment by M-Reimer** [comment]
Interesting find. I didn't have this in mind that an ampersand is used as special character.

Fixed in https://github.com/M-Reimer/undoclosetab/commit/f54c38e5a15d28d3f338aa01de42a21d60c8a57a
